src/Entity/Produit.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use App\Entity\Trait\SlugTrait;
use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;

#[ApiResource(normalizationContext: [
    'groups' => ['produits:read'],
])]
#[ORM\Entity(repositoryClass: ProduitRepository::class)]
#[ApiFilter(SearchFilter::class, properties: ['categorie' => 'exact'])]
#[ApiFilter(SearchFilter::class, properties: ['id' => 'exact'])]
class Produit
{
    use SlugTrait;
    
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['produits:read'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(['produits:read'])]
    private ?string $ShortLibel = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    #[Groups(['produits:read'])]
    private ?string $LongLibel = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 8, scale: 2, nullable: true)]
    #[Groups(['produits:read'])]
    private ?string $prxHt = null;

    #[ORM\Column(length: 255)]
    #[Groups(['produits:read'])]
    private ?string $slug = null;

    #[ORM\OneToMany(mappedBy: 'RefProduit', targetEntity: Photo::class,
    orphanRemoval: true, cascade:['persist'])]
    #[Groups(['produits:read'])]

    private Collection $photos;

    #[ORM\OneToMany(mappedBy: 'RefProduit', targetEntity: LigneCommande::class, orphanRemoval: true)]
    private Collection $ligneCommandes;

    #[ORM\OneToMany(mappedBy: 'RefProduit', targetEntity: Liste::class)]
    private Collection $listes;

    #[ORM\OneToMany(mappedBy: 'RefProduit', targetEntity: Stock::class)]
    private Collection $stocks;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(['produits:read'])]
    
    private ?Categorie $categorie = null;


    public function __construct()
    {
        $this->photos = new ArrayCollection();
        $this->ligneCommandes = new ArrayCollection();
        $this->listes = new ArrayCollection();
        $this->stocks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getShortLibel(): ?string
    {
        return $this->ShortLibel;
    }

    public function setShortLibel(string $ShortLibel): self
    {
        $this->ShortLibel = $ShortLibel;

        return $this;
    }

    public function getLongLibel(): ?string
    {
        return $this->LongLibel;
    }

    public function setLongLibel(?string $LongLibel): self
    {
        $this->LongLibel = $LongLibel;

        return $this;
    }

    public function getPrxHt(): ?string
    {
        return $this->prxHt;
    }

    public function setPrxHt(?string $prxHt): self
    {
        $this->prxHt = $prxHt;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, Photo>
     */
    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): self
    {
        if (!$this->photos->contains($photo)) {
            $this->photos->add($photo);
            $photo->setRefProduit($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): self
    {
        if ($this->photos->removeElement($photo)) {
            // set the owning side to null (unless already changed)
            if ($photo->getRefProduit() === $this) {
                $photo->setRefProduit(null);
            }
        }

        return $this;
    }


    /**
     * @return Collection<int, LigneCommande>
     */
    public function getLigneCommandes(): Collection
    {
        return $this->ligneCommandes;
    }

    public function addLigneCommande(LigneCommande $ligneCommande): self
    {
        if (!$this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes->add($ligneCommande);
            $ligneCommande->setRefProduit($this);
        }

        return $this;
    }

    public function removeLigneCommande(LigneCommande $ligneCommande): self
    {
        if ($this->ligneCommandes->removeElement($ligneCommande)) {
            // set the owning side to null (unless already changed)
            if ($ligneCommande->getRefProduit() === $this) {
                $ligneCommande->setRefProduit(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Liste>
     */
    public function getListes(): Collection
    {
        return $this->listes;
    }

    public function addListe(Liste $liste): self
    {
        if (!$this->listes->contains($liste)) {
            $this->listes->add($liste);
            $liste->setRefProduit($this);
        }

        return $this;
    }

    public function removeListe(Liste $liste): self
    {
        if ($this->listes->removeElement($liste)) {
            // set the owning side to null (unless already changed)
            if ($liste->getRefProduit() === $this) {
                $liste->setRefProduit(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Stock>
     */
    public function getStocks(): Collection
    {
        return $this->stocks;
    }

    public function addStock(Stock $stock): self
    {
        if (!$this->stocks->contains($stock)) {
            $this->stocks->add($stock);
            $stock->setRefProduit($this);
        }

        return $this;
    }

    public function removeStock(Stock $stock): self
    {
        if ($this->stocks->removeElement($stock)) {
            // set the owning side to null (unless already changed)
            if ($stock->getRefProduit() === $this) {
                $stock->setRefProduit(null);
            }
        }

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }



   



}

src/Controller/Admin/ProductsController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Photo;
use App\Entity\Produit;
use App\Form\ProductsFormType;
use App\Repository\CategorieRepository;
use App\Repository\ProduitRepository;
use App\Service\PictureService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

#[Route('/admin/products', name: 'admin_products_')]
class ProductsController extends AbstractController{

    #[Route('/', name:'index')]
    public function index(ProduitRepository $produitRepository, CategorieRepository $categorieRepository): Response
    {
        return $this->render('admin/products/index.html.twig',[
            'produits' => $produitRepository->findBy([],['id' => 'asc']), 
            'surCategories' => $categorieRepository->findBy(['parent' => null]),
        'SubCategories' => $categorieRepository->createQueryBuilder('c')
        ->where('c.parent IS NOT NULL')
        ->getQuery()
        ->getResult(),
        ]);
    }

    #[Route('/add', name:'add')]
    public function add(CategorieRepository $categorieRepository, Request $request, EntityManagerInterface $em, SluggerInterface $slugger): Response
    {

        //création d'un nouveau produit 
        $product = new Produit();

        // Création du formulaire 
        $productform = $this->createForm(ProductsFormType::class, $product);

        //On traite la requête du formulaire
        $productform->handleRequest($request);
       
        // Vérification si formulaire est soumis et valide 
        if($productform ->isSubmitted() && $productform->isValid()){
            //Création du slug 
            $slug = $slugger->slug($product->getShortLibel());
            $product->setSlug($slug);

            $em->persist($product);
            $em->flush();
            $this->addFlash('Success', 'Product added with success !');
            
            //on redirige 
            return $this->redirectToRoute('admin_products_index');
        }

        return $this->render('admin/products/add.html.twig',[
            'productform' => $productform->createView(),
            'surCategories' => $categorieRepository->findBy(['parent' => null]),
            'SubCategories' => $categorieRepository->createQueryBuilder('c')
                ->where('c.parent IS NOT NULL')
                ->getQuery()
                ->getResult(),
        ]);
        
    }

    #[Route('/edit/{id}', name:'edit')]
    public function edit(Produit $product,CategorieRepository $categorieRepository, Request $request, EntityManagerInterface $em, SluggerInterface $slugger, PictureService $pictureService): Response
    {

        // Création du formulaire 
        $productform = $this->createForm(ProductsFormType::class, $product);

        //On traite la requête du formulaire
        $productform->handleRequest($request);
       
        // Vérification si formulaire est soumis et valide 
        if($productform ->isSubmitted() && $productform->isValid()){

            //Récupération des images 
            $photos = $productform->get('photos')->getData();
            $cpt=1;
            foreach ($photos as $photo) {
                $folder = 'products';     
                $fichier=$pictureService->add($photo,$folder,300,300);
                $img = new Photo();
                $img->setSrc($fichier);
                $product->addPhoto($img);


                if($cpt==1 ){
                    $img->setIsPrimary(1);
                }else{
                    $img->setIsPrimary(0);
                }
                $cpt++;

            }   
            //Création du slug 
            $slug = $slugger->slug($product->getShortLibel());
            $product->setSlug($slug);

            $em->persist($product);
            $em->flush();
            $this->addFlash('Success', 'Product Edited with success !');
            
            //on redirige 
            return $this->redirectToRoute('admin_products_index');
        }

        return $this->render('admin/products/edit.html.twig',[
            'productform' => $productform->createView(), 
            'produit' => $product,
            'surCategories' => $categorieRepository->findBy(['parent' => null]),
            'SubCategories' => $categorieRepository->createQueryBuilder('c')
                ->where('c.parent IS NOT NULL')
                ->getQuery()
                ->getResult(),
        ]);
        
        
    }
    #[Route('/delete/{id}', name:'delete')]
    public function delete(CategorieRepository $categorieRepository, Produit $product): Response
    {
        return $this->render('admin/products/index.html.twig',[
            'surCategories' => $categorieRepository->findBy(['parent' => null]),
            'SubCategories' => $categorieRepository->createQueryBuilder('c')
                ->where('c.parent IS NOT NULL')
                ->getQuery()
                ->getResult(),
        ]);
        
    }
}

src/Controller/ProductsController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Entity\Produit;
use App\Repository\CategorieRepository;
use App\Repository\ProduitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response ;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/products', name:'app_products_')]
class ProductsController extends AbstractController{


    #[Route('/', name:'index')]
    public function index(ProduitRepository $produitRepository, CategorieRepository $categorieRepository): Response
    {
        return $this->render('products/index.html.twig',[
            'produits' => $produitRepository->findBy([],['id' => 'asc']), 
            'surCategories' => $categorieRepository->findBy(['parent' => null]),
        'SubCategories' => $categorieRepository->createQueryBuilder('c')
        ->where('c.parent IS NOT NULL')
        ->getQuery()
        ->getResult(),
        ]);
    }
    
    #[Route('/{slug}', name: 'details')]
    public function details(Produit $produit,ProduitRepository $produitRepository, CategorieRepository $categorieRepository): Response{
        $categoriesProduit = $produitRepository->findBy(['categorie' => $produit->getCategorie()]);
        $surCategories = $categorieRepository->findBy(['parent' => null]);
        $SubCategories = $categorieRepository->createQueryBuilder('c')
                        ->where('c.parent IS NOT NULL')
                        ->getQuery()
                        ->getResult();;

    return $this->render('products/details.html.twig', compact('produit', 'categoriesProduit', 'surCategories', 'SubCategories'));
    }
    


}

templates/products/details.html.twig
{% extends "base.html.twig" %}

{% block title %}
	{{produit.shortLibel}}
{% endblock %}

{% block body %}
	<div class="container-fluid tshadow mt-5 pt-5 bg-Ardoise mt-0">
		<div class="row">
			<div class="col-lg-4">
				<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
					<div class="carousel-indicators">
						{% for photo in produit.photos %}
							<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ loop.index0 }}" class="active" aria-current="{{ loop.first ? 'true' : 'false' }}" aria-label="Slide {{ loop.index }}"></button>
						{% endfor %}
					</div>
					<div class="carousel-inner">
						{% for photo in produit.photos %}
							<div class="carousel-item {{ loop.first ? 'active' }}">
								<img class="d-block w-100" src="{{ photo.src }}" alt="{{ produit.shortLibel }}">
							</div>
						{% endfor %}
					</div>
					<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Previous</span>
					</button>
					<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="visually-hidden">Next</span>
					</button>
				</div>
				<div class="row mt-3 mb-3">
					{% for photo in produit.photos %}
						<div class="col-2 mt-2">
							<img src="{{ photo.src }}" class="d-block w-100" alt="{{ produit.shortLibel }}" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ loop.index0 }}">
						</div>
					{% endfor %}
				</div>
			</div>

			<div class="col-lg-8 text-left">
				<div class="d-flex flex-row me-2 justify-content-between">

					<div class="HolographicEffect titleFont">
						<h1 data-text="{{ produit.shortLibel|split(' ')|join(' ') }}">{{ produit.shortLibel }}</h1>
					</div>
					<div class="font-weight-bold retro-chrome text-light">
						<span>
							{{ produit.prxHt }}€</span>
						<span>{{ produit.prxHt }}€</span>

					</div>
				</div>


				<div class="mt-4 txt-LightGrey text-justify description font-serif mb-5 ">
					{{ produit.longLibel }}
				</div>
				<a href="{{ path('app_cart_add', {'id':produit.id}) }}" type="button" class="btn-AddToCauldron mt-5 text-center card-text LargeFont">Add to cauldron</a>
			</div>

		</div>

	</div>

	<div class="container lovingIt">
		<div class="row mb-5">
			<div class="col-lg-12">
				<h2 class="mb-4">You could also love</h2>
			</div>

			{% set randomProducts = categoriesProduit|shuffleArray|filter(p => p.slug != produit.slug)|slice(0,6) %}


			{% for prodCat in randomProducts %}
				<div class="col-lg-2 col-md-4 col-6 mb-4">
					<div class="card h-100">
						{% set primaryPhoto = prodCat.photos|filter(p => p.isPrimary is not null and p.isPrimary)|first %}
						<div class="parentRelatif cardImgSeller">
							<a href="{{ prodCat.slug }}">
								{% if primaryPhoto.src[:4] == 'http' %}
									<img src="{{ primaryPhoto.src }}" alt="{{ produit.shortLibel }}" class="card-img-center img-fluid">

								{% else %}
									<img src="{{ asset('assets/uploads/products/mini/300x300-' ~ primaryPhoto.src ) }}" alt="{{ produit.shortLibel }}" class="card-img-center img-fluid">

								{% endif %}
							</a>
						<a href="{{ path('app_cart_add', {'id':produit.id}) }}" type="button" class="card-text LargeFont">Add to cauldron</a>
							{% if prodCat.photos|length > 1 %}
								{% set secondaryPhotos = prodCat.photos|filter(p => p.isPrimary is null) %}
								{% for photo in secondaryPhotos %}
									<div class="secondary-photo" style="display: none;">
										{% if photo.src[:4] == 'http' %}
											<img src="{{ primaryPhoto.src }}" alt="{{ produit.shortLibel }}" class="card-img-center img-fluid">

										{% else %}
											<img src="{{ asset('assets/uploads/products/mini/300x300-' ~ primaryPhoto.src ) }}" alt="{{ produit.shortLibel }}" class="card-img-center img-fluid">

										{% endif %}
									</div>
								{% endfor %}
							{% endif %}
						</div>
						<div class="card-body">
							<div class="font-serif">{{ prodCat.shortLibel }}</div>
							<div>{{ prodCat.prxHt }}€</div>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>


	{% include "_partials/_footer.html.twig" %}
{% endblock %}

templates/products/index.html.twig
{% extends "base.html.twig" %}

{% block title %}Produits{% endblock %}

{% block body %}

<div class="container bestSeller">
    <div class="row pt-5 bg-Ardoise">
        {% for produit in produits %}
			<div class="col-lg-3 mb-5 col-md-6">
				<div class="card" data-images="{{ produit.photos|map(p => p.src)|join(',') }}">

					<div class="parentRelatif cardImgSeller">
						<a id="ancre" href="{{ path('app_products_details', {'slug':produit.slug}) }}">

							{% for photo in produit.photos %}

								{% if photo.src[:4] == 'http' %}
									<img src="{{ photo.src }}" alt="{{ produit.shortLibel }}" class="d-block h-100 d-inline-block card-img-top img-fluid w-100 ">

								{% else %}
									<img src="{{ asset('assets/uploads/products/mini/300x300-' ~ photo.src ) }}" alt="{{ produit.shortLibel }}" class="d-block h-100 d-inline-block card-img-top img-fluid w-100 ">

								{% endif %}
							{% endfor %}

						</a>
						<a href="{{ path('app_cart_add', {'id':produit.id}) }}" type="button" class="card-text LargeFont">Add to cauldron</a>
					</div>
					<div class="card-body">
						<div class="font-serif">{{ produit.shortLibel }}</div>
						<div>{{ produit.prxHt }}€</div>
					</div>
				</div>
			</div>
		{% endfor %}
    </div>
</div>
{% include "_partials/_footer.html.twig" %}
{% endblock %}

templates/products/sousCategorie.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
<div class="container bestSeller">
    <div class="row pt-5 bg-Ardoise">
       {% for produit in produits %}
			<div class="col-lg-3 mb-5 col-md-6">
				<div class="card" data-images="{{ produit.photos|map(p => p.src)|join(',') }}">

					<div class="parentRelatif cardImgSeller">
						<a id="ancre" href="{{ path('app_products_details', {'slug':produit.slug}) }}">

							{% for photo in produit.photos %}

								{% if photo.src[:4] == 'http' %}
									<img src="{{ photo.src }}" alt="{{ produit.shortLibel }}" class="d-block h-100 d-inline-block card-img-top img-fluid w-100 ">

								{% else %}
									<img src="{{ asset('assets/uploads/products/mini/300x300-' ~ photo.src ) }}" alt="{{ produit.shortLibel }}" class="d-block h-100 d-inline-block card-img-top img-fluid w-100 ">

								{% endif %}
							{% endfor %}

						</a>
						<a href="{{ path('app_cart_add', {'id':produit.id}) }}" type="button" class="card-text LargeFont">Add to cauldron</a>
					</div>
					<div class="card-body">
						<div class="font-serif">{{ produit.shortLibel }}</div>
						<div>{{ produit.prxHt }}€</div>
					</div>
				</div>
			</div>
		{% endfor %}
    </div>
</div>
{% endblock %}